users/urls.py
from django.urls import path , include
from users import views


app_name = "users"

urlpatterns = [
    path('login/',views.login,name="login"),
    path('logout/', views.logout,name="logout"),
    path('signup/', views.signup,name="signup"), 
    path('terms_and_conditions/', views.t_and_c,name="t_and_c"), 

    path("send_otp",views.send_otp,name="send otp"),
]

web/urls.py
from django.urls import path , include

from web import views


app_name = "web"

urlpatterns = [
	path('', views.index,name="index"),
    path('adil/', views.adil, name='adil'),
    path('view/', views.view_all_created, name='view_all_created'),
    path("view/add_wiki/", views.add_wiki, name="add_wiki"),
    path('<int:id>/<slug:slugged>/', views.wikidetail, name='wiki_detail'),
    path('delete/', views.view_after_delete,name="view_after_delete"),
    path("view/delete_post/<int:id>/", views.delete_post, name="delete_post")
]

wiki/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path as url
from django.views.static import serve

from users import views 


handler404 = 'users.views.custom_page_not_found_view'
handler500 = 'users.views.custom_error_view'
handler403 = 'users.views.custom_permission_denied_view'
handler400 = 'users.views.custom_bad_request_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include("users.urls",namespace="users")),
    path('', include("web.urls",namespace="web")),
    path("send_otp",views.send_otp,name="send otp"),
    # path('posts/', include("posts.urls",namespace="posts")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]
if settings.DEBUG:
	urlpatterns += (
	static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) +
	static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) 
)

templates/web/after_delete.html
<!DOCTYPE html>
<html lang="en" style="overflow-x: hidden;" >
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <title>Delete Page</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/logo-of-both-removebg-preview.png' %}">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body  style="overflow-x: hidden;" class="min-h-full block max-h-full for_main_body">
        <section id="full-here">
            <section class="for_second_bg">
                <nav class="flex items-center justify-between flex-wrap p-6">
                    <div class="flex items-center flex-shrink-0 text-black mr-6">
                        <a href="{% url 'web:index' %}">
                            <div class="main-logo block w-[120px] max-w-md">
                                <img src="{% static 'images/logo-of-both-removebg-preview.png' %}" alt="main logo" />
                            </div>
                        </a>
                    </div>
                    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
                        <div class="text-sm lg:flex-grow">
                            <a href="{% url 'web:view_all_created' %}" class="font-bold block mt-4 lg:inline-block lg:mt-0 decoration-green-200 hover:text-black mr-4">Create</a>
                        </div>
                    <div>
                        <a href="{% url 'users:logout' %}" class="inline-block text-sm px-4 py-2 leading-none border rounded text-black border-black hover:border-transparent font-bold hover:text-teal-500 hover:bg-black mt-4 lg:mt-0">Log Out</a>
                    </div> 
                    </div>
                </nav>

                <section class="top-of-wrapper grid place-items-center h-screen max-h-96 min-h-96 text-center content-center ">

                    <section class="wrapper font-serif 	 font-bold">

                        <h1>Do you want to create a new one</h1>
                        <h3>There are certain steps</h3>
                        <h3>Delete the current wiki page</h3>
                        <h3>Then create new page from here</h3>
    
                        {% if post.deleted %}
                            <p>Post has been deleted</p>
                            <a href="{% url 'web:add_wiki' %}" class=" my-1 inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" >Create New POST</a>
                        {% else %}
                            <a href="{% url 'web:view_all_created' %}" class="mt-[10px] inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Create New Post</a>
                        {% endif %}
                    </section>  <!-- .wrapper -->
                </section>

                <div class="for-bg-awesome">
                    <div class="shapes animate-shapes bubble">
                        <img src="{% static 'images/custom1.png' %}" alt="shape-bubble" />
                    </div>
                    <div class="shapes animate-shapes hexa">
                        <img src="{% static 'images/custom2.png' %}" alt="shape-hexa" />
                    </div>
                    <div class="shapes animate-shapes three-shapes">
                        <img src="{% static 'images/custom3.png' %}" alt="shape-three-shapes" />
                    </div>
                    <div class="shapes animate-shapes tria">
                        <img src="{% static 'images/custom4.png' %}" alt="shape-tria" />
                    </div>
                    <div class="shapes animate-shapes hexa-out">
                        <img src="{% static 'images/custom22.png' %}" alt="shape-hexa-out" />
                    </div>
                    <div class="shapes animate-shapes love-shape">
                        <img src="{% static 'images/custom55.png' %}" alt="love-shape" />
                    </div>
                    <div class="shapes animate-shapes three-new-shapes">
                        <img src="{% static 'images/custom66.png' %}" alt="shape-three-new-shapes" />
                    </div>
                </div>

        </section> <!-- #view-full-here ended here -->
        <div class="bottom-tandc">
            <a href="{% url 'users:t_and_c' %}" class="tandc">Terms and Conditions</a>
            <a href="{% url 'web:adil' %}" class="akt16">Creator</a>
            <a href="{% url 'users:t_and_c' %}" class="tandc pp">Privacy policy</a>
        </div>
        
    </body>
</html>

templates/web/create.html
<!DOCTYPE html>
	<html lang="en">
		<head>
			{% load static %}
			<meta charset="UTF-8" />
			<title>WIKI Post | Create your WIKI</title>
			<link rel="stylesheet" href="{% static 'css/style.css' %}" />
			<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/Adil A.png' %}" />     
			<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			<meta property="og:image" content="" />
			<meta name="description" content="" />
			<meta name="keywords" content="" />
			<link rel="icon" type="image/x-icon" href="{% static 'images/logo-of-both-removebg-preview.png' %}">
			<style>
				.upload-button {
				/* Used to position the input */
				position: relative;

				/* Center the content */
				align-items: center;
				display: flex;

				/* Border */
				border: 1px solid #d1d5db;
				border-radius: 0.25rem;
				padding: 0.25rem 0.5rem;
				cursor: pointer;
				border: 1px solid #000;

			}

			.upload-button__input {
				/* Take the full size */
				height: 100%;
				cursor: pointer;	
				border: 1px solid #000;
				left: 0;
				position: absolute;
				top: 0;
				width: 100%;

				/* Make it transparent */
				opacity: 0;
			}

			.upload-button__icon {
				margin-right: 0.5rem;
			}
			.custom-checkbox-button {
				/* Center the content horizontally */
				align-items: center;
				display: inline-flex;

				/* Cursor */
				cursor: pointer;
			}

			.custom-checkbox-button__input {
				/* Hide it */
				display: none;
			}

			.custom-checkbox-button__square {
				border: 1px solid #d1d5db;
				border-radius: 0.25rem;

				/* Spacing */
				margin-right: 0.5rem;
				padding: 0.25rem;
			}

			.custom-checkbox-button__checkbox {
				background-color: transparent;
				border-radius: 0.25rem;
				height: 1rem;
				width: 1rem;
			}

			.custom-checkbox-button__checkbox--selected {
				/* For selected checkbox */
				background-color: #3b82f6;
			}
			</style>
		</head>
		<body> 
			
			<section id="edit-post-home">
				<section class="wrapper">
					<section class="spotlight">
						<h3 class="create_heading" style="display: block;" >Create new post</h3>

						<section class="banner-ad ad-one">
							<div class="for-centering-ad">
								<a href="https://steyp.com/" target="_blank" >
									<div class="banner-ad-container">
										<img src="{% static 'images/ads/steyp-logo.svg' %}" alt="steyp ad" />
									</div>
								</a>
								<a href="https://www.lasaguapp.in/" target="_blank" >
									<div class="banner-ad-container">
										<img src="{% static 'images/ads/lasagu-banner.png' %}" alt="steyp ad" />
									</div>
								</a>
							</div>
						</section>
						
						<form action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="form-field">
								{{ form.as_p }}
							</div>
							<section class="agree_terms">
								<p>By submitting , you have agreed to our terms and conditions</p>
							</section>
							<div style="margin-top: 10px;" class="form-field">
								<input type="submit" value="Submit" />
							</div>
						</form>


						
						<div class="for-home">
							<a href="{% url 'web:view_all_created'  %}"><button>Home</button></a>
						</div>
					</section> <!-- .spotlight ended here -->
					
				</section>
			</section>
			<section class="for-termsandconditions">
				<div class="grouping-all">
					<a href="{% url 'users:t_and_c' %}"><span>Terms and conditions</span></a>
					<a href="{% url 'users:t_and_c' %}"><span>Privacy Policy</span></a>
					<a href="{% url 'web:adil' %}"><span>About Creator</span></a>
					<a target="blank" href="mailto:adilkt16@gmail.com"><span>Give Ads</span></a>
				</div>
			</section>
			<script>
				const textarea = document.getElementById("myTextarea");
				const charCount = document.getElementById("charCount");

				textarea.addEventListener("input", function() {
				const text = textarea.value;
				charCount.textContent = text.length;
				});
			</script>
		</body>
	</html>

templates/web/index.html
<!DOCTYPE html>
<html lang="en" style="overflow-x: hidden;" >
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="icon" type="image/x-icon" href="{% static 'images/logo-of-both-removebg-preview.png' %}">
        <title>WIKI_Page AKT16</title>
    </head>
    <body  style="overflow-x: hidden;" class="for_main_body">
        <section id="full-here">
            <section class="for_second_bg">
                <header class="main-page-header">
                    <ul>
                        <li>
                            <a href="{% url 'web:index' %}">
                                <div class="main-logo">
                                    <img src="{% static 'images/logo-of-both-removebg-preview.png' %}" alt="main logo" />
                                </div>
                            </a>
                        </li>

                        
                        <li>
                            <div class="both-icon-and-username">
                                <div class="username-user">
                                    {% if request.user.is_authenticated %}

                                    <h3  class="if_else_user_logged"   >{{request.user.username}}</h3>
                                    <a href="{% url 'users:logout' %}"   class="if_else_login">Log out</a>

                                    {% else %}

                                    <a href="{% url 'users:login' %}"   class="if_else_login">Log In</a>
                                    <!-- <h3  class="if_else_user_logged"   >Username</h3> -->

                                    {% endif %}
                                </div>
                            </div>
                        </li>
                    </ul>
                </header>
                <section class="wrapper">
                    <section id="main-view-full">
                        <div class="spotlight-both">
                            <div class="left-detail">
                                <h1 class="main-heading-for-site">Create Your <br /> <span class="special-styling">Wiki </span> Page </h1>
                                
                                <div class="video-container-for-detail-none">
                                    <video   controls poster="{% static 'images/coach username.png' %}" >
                                        <source src="{% static 'video/explainer.mp4' %}" type="video/mp4" />
                                    </video>
                                </div>

                                <h3 class="why-choose">Why create a <span class="special-styling">Wiki</span>  Page?</h3>
                                <p class="detail-of-wiki">
                                    Having a Wikipedia page can increase visibility and reach for individuals and organizations by providing a platform for sharing information about their accomplishments, contributions, and history.
                                </p>
                                {% if request.user.is_authenticated %}
                                    <a href="{% url 'web:view_all_created' %}" class="button-for-join">Create Now</a>
                                    {% else %}
                                    <a href="{% url 'users:login' %}" class="button-for-join">Create Now</a>
                                {% endif %}
                            </div>
                            <div class="right-video">
                                <div class="video-container-for-detail">
                                    <video   controls poster="{% static 'images/coach username.png' %}" >
                                        <source src="{% static './video/explainer.mp4' %}" type="video/mp4" />
                                    </video>
                                </div> 
                            </div>
                        </div> <!-- div.spotlight-both ended -->
                    </section> <!-- #main-view-full -->
                    <div class="for-external-bg">
                        
                    </div>
                    
                </section> <!-- .wrapper ended -->
                <div class="for-bg-awesome">
                    <div class="shapes animate-shapes bubble">
                        <img src="{% static 'images/custom1.png' %}" alt="shape-bubble" />
                    </div>
                    <div class="shapes animate-shapes hexa">
                        <img src="{% static 'images/custom2.png' %}" alt="shape-hexa" />
                    </div>
                    <div class="shapes animate-shapes three-shapes">
                        <img src="{% static 'images/custom3.png' %}" alt="shape-three-shapes" />
                    </div>
                    <div class="shapes animate-shapes tria">
                        <img src="{% static 'images/custom4.png' %}" alt="shape-tria" />
                    </div>
                    <div class="shapes animate-shapes hexa-out">
                        <img src="{% static 'images/custom22.png' %}" alt="shape-hexa-out" />
                    </div>
                    <div class="shapes animate-shapes love-shape">
                        <img src="{% static 'images/custom55.png' %}" alt="love-shape" />
                    </div>
                    <div class="shapes animate-shapes three-new-shapes">
                        <img src="{% static 'images/custom66.png' %}" alt="shape-three-new-shapes" />
                    </div>
                </div>
            </section>
        </section>
        <div class="bottom-tandc">
            <a href="{% url 'users:t_and_c' %}" class="tandc">Terms and Conditions</a>
            <a href="{% url 'web:adil' %}" class="akt16">Creator</a>
            <a href="{% url 'users:t_and_c' %}" class="tandc pp">Privacy policy</a>
        </div>
    </body>
</html>