users/urls.py
from django.urls import path , include
from users import views


app_name = "users"

urlpatterns = [
    path('login/',views.login,name="login"),
    path('logout/', views.logout,name="logout"),
    path('signup/', views.signup,name="signup"), 
    path('terms_and_conditions/', views.t_and_c,name="t_and_c"), 

    path("send_otp",views.send_otp,name="send otp"),
]

web/urls.py
from django.urls import path , include

from web import views


app_name = "web"

urlpatterns = [
	path('', views.index,name="index"),
    path('adil/', views.adil, name='adil'),
    path('view/', views.view_all_created, name='view_all_created'),
    path("view/add_wiki/", views.add_wiki, name="add_wiki"),
    path('<int:id>/<slug:slugged>/', views.wikidetail, name='wiki_detail'),
    path('delete/', views.view_after_delete,name="view_after_delete"),
    path("view/delete_post/<int:id>/", views.delete_post, name="delete_post")
]

wiki/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path as url
from django.views.static import serve

from users import views 


handler404 = 'users.views.custom_page_not_found_view'
handler500 = 'users.views.custom_error_view'
handler403 = 'users.views.custom_permission_denied_view'
handler400 = 'users.views.custom_bad_request_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include("users.urls",namespace="users")),
    path('', include("web.urls",namespace="web")),
    path("send_otp",views.send_otp,name="send otp"),
    # path('posts/', include("posts.urls",namespace="posts")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]
if settings.DEBUG:
	urlpatterns += (
	static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) +
	static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) 
)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ["username","password"] 
		widgets = {
                "password" : forms.widgets.PasswordInput(attrs={
                    "class":"",
                    "placeholder":"Enter your password"
                }) ,
				"username" : forms.widgets.TextInput(attrs={
                    "class":"",
                    "placeholder":"Replace space with underscore."
                }) ,
        }

users/views.py
from django.shortcuts import render , reverse
from django.contrib.auth import authenticate , login as auth_login , logout as auth_logout
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt


from users.forms import UserForm
from main.functions import generate_form_errors




def custom_page_not_found_view(request, exception):
    return render(request, "users/404.html", {})

def custom_error_view(request, exception=None):
    return render(request, "users/404.html", {})

def custom_permission_denied_view(request, exception=None):
    return render(request, "users/404.html", {})

def custom_bad_request_view(request, exception=None):
    return render(request, "users/404.html", {})

@csrf_exempt
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request,username=username,password=password)
            if user is not None:
                auth_login(request,user)
                return HttpResponseRedirect(reverse("web:view_all_created"))
            else:
                context = {
                    "title" : "Login",
                    "error" : True,
                    "message" : "Invalid username or password"
                }
                return render(request,"users/login.html",context=context)
        else:
            context = {
                "title" : "Login",
                "error" : True,
                "message" : "Invalid username or password"
            }
            return render(request,"users/login.html",context=context)
    context = {
        "title" : "Log inned"
    }
    return render(request,"users/login.html",context=context)




from django.shortcuts import render , reverse
from django.http.response import HttpResponseRedirect

@csrf_exempt
def logout(request):
	auth_logout(request)
	return HttpResponseRedirect(reverse("web:index"))


@csrf_exempt
def signup(request):
	if request.method == "POST":
		form = UserForm(request.POST)
		if form.is_valid():
			instance = form.save(commit=False)

			User.objects.create_user(
						username=instance.username,
						password=instance.password,
						email=instance.email,
			)

			user = authenticate(request,username=instance.username,password=instance.password)
			auth_login(request,user)
				
			return HttpResponseRedirect(reverse("web:view_all_created"))
		else:
			message = generate_form_errors(form)
			form = UserForm()    
			context = {
					"title" : "Signup" ,
					"error" : True,
					"message" : message,
					"form" : form,
			}
			return render(request,"users/signup.html",context=context)

	else:
		form = UserForm()   
		context = {
				"title" : "SIgnup",
				"form" : form,
		}
		return render(request,"users/signup.html",context=context)






from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
import math, random


@csrf_exempt
def generateOTP() :
	digits = "0123456789"
	OTP = ""
	for i in range(4) :
		OTP += digits[math.floor(random.random() * 10)]
	return OTP

@csrf_exempt
def send_otp(request):
	# email=request.POST.get("email")
	gmail=request.POST.get("email")
	email=request.GET.get("email")
	o=generateOTP()
	htmlgen = f'<p>Your OTP is <strong>{o}</strong></p>'
	result = send_mail('OTP request',o,'wikipageverify@gmail.com',[gmail],  fail_silently=False, html_message=htmlgen)

	return HttpResponse(o)




def t_and_c(request):
	context = {
		"title" : "Terms and conditions page",
	}
	return render(request,'users/terms.html')

templates/users/creatorAdil.html
<!DOCTYPE html>
<html lang="en" style="overflow-x: hidden;">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Creator (Adil)</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link rel="icon" type="image/x-icon" href="{% static 'images/good.png' %}">
    </head>
    <body>
        <section id="full-adil">
            <header class="main-page-header">
                <ul>
                    <li>
                        <a href="{% url 'web:index' %}">
                            <div class="main-logo">
                                <img src="{% static 'images/logo-of-both-removebg-preview.png' %}" alt="main logo" />
                            </div>
                        </a>
                    </li>
                </ul>
            </header>
            <section id="detail-of-adil">
                <div class="creator-img">
                    <img src="{% static 'images/creator/good.png' %}" alt="adil-image" />
                </div>
                <h1 class="name">ADIL KT</h1>
                <p class="stack">Fullstack Developer</p>
                <p class="my-details">Hello world, I'm 18 y/o passionate developer from Kerala, India who loves to bring ideas to life. I love to develop applications using cutting edge tech.</p>
                <div class="quick-contact">
                    <a href="mailto:adilkt16@gmail.com">
                        <div class="each-image">
                            <img src="{% static 'images/creator/black-gmail-logo.svg' %}" alt="gmail" />
                        </div>
                        <span class="logo-name">Email</span>
                    </a>
                    <a href="https://instagram.com/a_k_t_16">
                        <div class="each-image">
                            <img src="{% static 'images/creator/black-instagram.svg' %}" alt="instagram" />
                        </div>
                        <span class="logo-name">Instagram</span>
                    </a>
                </div>
                <section class="skills">
                    <h2 class="subs">Skills</h2>
                    <p>I'm doing this for almost 2 years from now, and I have learned a lot of things through this journey.</p>
                    <div class="all-divs">
                        <div class="each-skill">
                            <span class="skill-name">Javascript</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">HTML</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">CSS</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">REACT</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">PYTHON</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">DJANGO</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">SASS</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">BOOTSTRAP</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">REST_API</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">PWA</span>
                        </div>
                        <div class="each-skill">
                            <span class="skill-name">GIT</span>
                        </div>
                    </div>
                    <p>And much more...</p>
                </section>  <!-- #skills ended here -->
                <section class="projects">
                    <h2>Projects</h2>
                    <p>I've build many projects using different technologies. Here are some of my notable works.</p>
                    <a href="{% url 'web:index' %}">
                        <div class="one-complete">
                            <h6>Wiki Page &#127760;</h6>
                            <p class="project-para">A  Project in which user can login and create their wiki pedia page for free , and see other users who have created from the same site. 	 </p>
                        </div>
                    </a>
                    <a href="https://adilkt16.github.io/ar_logistics/">
                        <div class="one-complete">
                            <h6> AR Logistics &#127760;</h6>
                            <p class="project-para">A  Project in which user can login and create their wiki pedia page for free , and see other users who have created from the same site. 	 </p>
                        </div>
                    </a>
                </section> <!-- .projects ended -->
                <section class="contact">
                    <h2>Wanna Connect with me ?</h2>
                    <p>Feel free to connect with me anyway you like, I would love to meet new people.</p>
                    <a href="mailto:adilkt16@gmail.com" class="gmail">adilkt16@gmail.com</a>
                    <div class="all-contact-methods">
                        <a href="https://www.linkedin.com/in/adilkt16/" class="each-contact">Linkedin</a>
                        <a href="mailto:adilkt16@gmail.com" class="each-contact">Email</a>
                        <a href="https://www.instagram.com/a_k_t_16/" class="each-contact">Instagram</a>
                        <!-- <a href="#" class="each-contact">Telegram</a> -->
                    </div>
                </section>
            </section> <!-- #detail-of-adil ended here -->
        </section> <!-- #full-adil ended here -->
    </body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html style="overflow-x: hidden;" lang="en" class="for_html">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/logo-of-both-removebg-preview.png' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type='text/javascript'></script>
    </head>
    <body  style="overflow-x: hidden;">
        <section id="login_complete">
            <section class="wrapper">
                <h1 class="login_heading">Login</h1>
                <section class="both-ad-and-input">
                    <section class="single-input-full">
                        <form action="" method="post" >
                            {% csrf_token %}
                            <div id="form_div" style="display: unset;" >
                                <label class="for_username_Class" for="username">Username</label>
                                <input class="for_input_username" type="text" name="username" id="username" />
                                <label class="for_password_Class" for="password">Password</label>
                                <input class="for_input_password" type="password" name="password" id="password" />
                                <input class="for_input_submit" type="submit" value="Log In">
                            </div>
                        </form>
                        
                        <div class="already_account">
                            <p class="already">If you dont have an Account</p>
                            <a href="{% url 'users:signup' %}" class="login_button">SignUp</a>
                            <a href="{% url 'web:index' %}" class="login_button">Home</a>
                        </div>
                    </section>
                    <section id="add-section" class="login_ad_image" >
                        <a target="blank" href="https://steyp.com"><img src="{% static 'images/ads/steyp.jpeg' %}" alt="steyp_ad_image" /></a>
                        
                    </section>
                </section> <!-- section.both-ad-and-input ended here  -->
                
            </section>
        </section>
        
    </body>
</html>

templates/users/signup.html
<!DOCTYPE html>
<html lang="en"  style="overflow-x: hidden;" class="for_html">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sign Up</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/logo-of-both-removebg-preview.png' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type='text/javascript'></script>
    </head>
    <body  style="overflow-x: hidden;">
        
        <section id="login_complete">
            <section class="wrapper">
                <h1 class="login_heading">Create Your Account</h1>
                <div id="email_div" style="display: block;" >
                    <label for="email">Email</label>
                    <div class="for_flexing">
                        <input type="text" class="for_retaining value" name="email" id="email">
                        <button  onclick="ajax_send_otp()">Send OTP</button>
                    </div>
                </div>
                <div id="verify_text_div"></div>
                <div id="otp_div" style="display: none;" >
                    <!-- change unset -->
                    <label for="email">OTP</label>
                    <div class="for_flexing_otp">
                        <input type="text" name="otp" id="otp">
                        <button  onclick="verify_otp()">Verify</button>
                    </div>
                </div>
                <br>
                <section class="both-ad-and-input">
                    <section class="single-input-full">

                        <div id="form_div" style="display: none;" >
                            <form action="" method="post">
                                {% csrf_token %}
                                <div>
                                {% for field in form  %}
                                    <div class="all-here"> 
                                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                                        {{field}}
                                    </div>
                                {% endfor %}
                                    <div class="submit">
                                        <button class="login_button" type="submit" >Sign In</button>
                                    </div>
                                </div>
                            </form>
                            <!-- change unset -->
                        </div>
                        
                    </section>
                    <section id="add-section" style="display: unset;">
                        <a target="blank" href="https://www.lasaguapp.in/"><img src="{% static 'images/ads/lasagu.jpg' %}" alt="lasagu_ad_image" /></a>
                        
                    </section>
                    
                </section>
                <div class="already_account">
                    <p class="already">If you already have an Account</p>
                    <a href="{% url 'users:login' %}" class="login_button">Login</a>
                    <a href="{% url 'web:index' %}" class="login_button">Home</a>
                </div>
                
                
            </section>
        </section>

        <!-- SND ALL UNSET TO NONE IN THIS PAGE -->
        <script>
            var otp_from_back="";
            function ajax_send_otp(){
                document.getElementById("email_div");
                email = document.getElementById("email");
                $.post("/send_otp",
                    {
                        "email":email.value,
                        "csrfmiddlewaretoken":"{{csrf_token}}"
                    },
                    function(data, status){
                        if(status=="success"){
                            otp_from_back = data;
                            document.getElementById("otp_div").style.display='block';
                            }
                }
                );
            }
            function verify_otp(){
                var user_otp=document.getElementById("otp").value;
                if (user_otp==otp_from_back){
                    document.getElementById("verify_text_div").style.color="green";            
                    document.getElementById("verify_text_div").innerHTML="OTP Verified";
                    document.getElementById("otp_div").style.display="none";
                    document.getElementById("form_div").style.display="block";
                }
                else{
                    document.getElementById("verify_text_div").style.color="red";
                    document.getElementById("verify_text_div").innerHTML="Try Again!!";
                }
            } 
        </script>
    </body>
</html>

templates/users/terms.html
<!DOCTYPE html>
<html lang="en" style="overflow-x: hidden;" >
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <title>Terms and Conditions</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/logo-of-both-removebg-preview.png' %}">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body  style="overflow-x: hidden;" class=" block  for_main_body">
        <section id="full-here">
            <section class="for_second_bg ">
                <nav class="block mx-auto w-max	 p-6">
                    <div class="flex items-center flex-shrink-0 text-black mr-6">
                        <a href="{% url 'web:index' %}">
                            <div class="main-logo block w-[120px] max-w-md">
                                <img src="{% static 'images/logo-of-both-removebg-preview.png' %}" alt="main logo" />
                            </div>
                        </a>
                    </div>
                </nav>

                <section class="top-of-wrapper   text-center  ">

                    <section class="wrapper font-serif  font-bold">

                        
                            <p>Terms / Privacy</p>
                            <a href="#terms" class=" my-1 inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" >Terms</a>
                        
                            <a href="#privacy" class="mt-[10px] inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Privacy</a>
                        
    
                            <div class="mx-auto  " id="terms" >
                                    <h1 class="text-2xl font-bold">Terms and Conditions</h1>
                                    
                                    <p class="">Welcome to <span class="font-bold">Wiki Page</span>! We are a listing fake wikipage website that provides a platform for users to share and view listings of various items and services. By accessing or using our website, you agree to be bound by the following terms and conditions:</p>
                                    <p class="">NB:We have no connection with the real site owners <span class="font-bold"><a href="https://www.wikipedia.org/" class="font-bold" target="_blank" >WikiPedia</a> </span></p>
                                    <ol class="list-decimal list-inside mb-4">
                                        <li class="mb-1">Acceptance of Terms: By accessing or using our website, you agree to these terms and conditions, as well as our Privacy Policy. If you do not agree with any of the terms or policies, please do not use our website.</li>
                                        <li class="mb-1">Use of Website: Our website is intended for personal, non-commercial use only. You may not use our website for any illegal or unauthorized purpose. You may not transmit any harmful or offensive content or interfere with the proper functioning of our website.</li>
                                        <li class="mb-1">User-Generated Content: Our website allows users to post listings and other content. By posting content, you represent and warrant that you have the right to do so, and that your content does not infringe on any third-party rights. We reserve the right to remove any content that we deem inappropriate or in violation of our policies.</li>
                                        <li class="mb-1">Intellectual Property: All content and materials on our website, including but not limited to text, graphics, logos, and images, are the property of <span class="font-bold">Wikipage</span> or its licensors. You may not use any content or materials on our website without our express written consent.</li>
                                        <li class="mb-1">Disclaimer of Warranties: Our website is provided "as is" and without any warranties of any kind, whether express or implied. We do not guarantee the accuracy, completeness, or timeliness of any content or materials on our website.</li>
                                        <li class="mb-1">Limitation of Liability: In no event shall <span class="font-bold">wiki Page</span> or its affiliates be liable for any direct, indirect, incidental, special, or consequential damages arising from the use of our website, including but not limited to damages for loss of profits, data, or other intangible losses.</li>
                                        <li class="mb-1">Indemnification: You agree to indemnify and hold <span class="font-bold">wiki Page</span> and its affiliates harmless from any and all claims, damages, liabilities, and expenses arising from your use of our website or any violation of these terms and conditions.</li>
                                        <li class="mb-1">Modifications: We reserve the right to modify these terms and conditions at any time. Any changes will be posted on our website, and your continued use of our website after the posting of any changes constitutes your acceptance of the modified terms and conditions.</li>
                                        <li>Governing Law: These terms and conditions are governed by the laws of <span class="font-bold">India</span>, and any dispute arising from these terms and conditions shall be resolved in the courts of <span class="font-bold">India</span>.</li>
                                    </ol>
                                
                                <p>If you have any questions or concerns contact us at <span class="font-bold">wikipageverify@gmail.com</span>. </p>
                            </div>

                            <div class="mt-3 mx-auto " id="privacy" >
                                    <h1 class="text-2xl font-bold ">Privacy Policy</h1>
                                
                                    <p class="mb-2">At <span class="font-bold">wiki Page</span>, we are committed to protecting the privacy and security of our users. This privacy policy explains how we collect, use, and protect your personal information. By accessing or using our website, you agree to this privacy policy:</p>
                                
                                    <ol class="list-decimal list-inside ">
                                        <li class="mb-1">Information We Collect: We collect information that you provide to us, such as your name, email address, and other contact information. We also collect information about your use of our website, such as your IP address and device information.</li>
                                        <li class="mb-1">How We Use Your Information: We use your information to provide and improve our website, communicate with you, and comply with legal requirements. We do not sell or share your personal information with third parties for their marketing purposes.</li>
                                        <li class="mb-1">Cookies and Tracking: We use cookies and other tracking technologies to analyze website usage and personalize content and advertising. You can control the use of cookies through your browser settings.</li>
                                        <li class="mb-1">Third-Party Links: Our website may contain links to third-party websites, which may have different privacy policies. We are not responsible for the content or privacy practices of these websites.</li>
                                        <li class="mb-1">Security: We take reasonable measures to protect your personal information from unauthorized access, disclosure, or alteration. However, no security measures are foolproof, and we cannot guarantee the security of your information.</li>
                                        <li>Changes to Privacy Policy: We reserve the right to modify this privacy policy at any time. Any changes will be posted on our website, and your continued use of our website after the posting of any changes constitutes your acceptance of the modified privacy policy.</li>
                                    </ol>
                                
                                    <p>If you have any questions or concerns about our privacy policy, please contact us at <span class="font-bold">wikipageverify@gmail.com</span>.</p>
                            </div>
    
                    </section>  <!-- .wrapper -->
                </section>

                


        </section> <!-- #view-full-here ended here -->
        <div class="bottom-tandc">
            <a href="{% url 'web:index' %}" class="tandc">Home</a>
            <a href="{% url 'web:adil' %}" class="akt16">Creator</a>
        </div>
        
    </body>
</html>